# Site settings
title: openCAESAR
author: Maged Elaasar 
description: Enabling Integrated Model Centric Engineering

# Site Url Settings
baseurl: ""

# Blog settings
paginate: 12
paginate_path: "/blog/page:num/"
blog_path: "/blog"

# Collection settings
collections:
  projects:
    output: true
  papers:
    output: true
  contributors:
    output: true
  events:
    output: true



# Build settings
sass:
    sass_dir: _sass
plugins: [jekyll-paginate] 


